package vars

const (
	MYSQL_ADDRESS  = "MYSQL_ADDRESS"
	MYSQL_USER     = "MYSQL_USER"
	MYSQL_PASSWORD = "MYSQL_PASSWORD"
	MYSQL_DATABASE = "MYSQL_DATABASE"

	INFLUX_ADDRESS   = "INFLUX_ADDRESS"
	INFLUX_TOKEN  = "INFLUX_TOKEN"
	INFLUX_ORG    = "INFLUX_ORG"
	INFLUX_BUCKET = "INFLUX_BUCKET"

	SERVICE_PORT = "SERVICE_PORT"
	SERVICE_NAME = "SERVICE_NAME"
)
